[package]
name = "python_core_console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_python_native = { path = "core_python_native", package = "core_python_native" }

